### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by tlf30** [tlf30/jme4#3]
1. Prepwork/Postwork
* [x]  Re-brand to JME4
* [ ]  Remove all deprecated libraries/classes/functions from jme3
* [x]  Remove `jme3-jbullet`
* [x]  Remove `jme3-lwjgl`
* [ ]   Remove `jme3-blender`
* [ ]   Remove `jme3-bullet*` replaced with Minie #9 
* [ ]  Remove old animation system
* [ ]  Format all code to a common format (POSTWORK)
* [ ]  Create a `JME4` issues tag on GitHub (POSTWORK)
* [ ]  Create a `4.0` branch on GitHub (POSTWORK)

2. JDK 11
~~* [ ]  Move to Gradle 5~~ DONE IN JME3
* [ ]  Implement java 9+ modules

3. Vulkan Support
* [ ]  Add abstraction layer between the rendering engine and the rest of jme
* [ ]  Abstraction layer tests
* [ ]  Get OpenGL working in the new rendering layer
* [ ]  Get Vulkan working in the new rendering layer
* [ ]  Add basic Vulkan shaders
* [ ]  Vulkan tests

4. Platform Support (need to get working in JME4)
* [ ]  Windows
* [ ]  Linux
* [ ]  OS X
* [ ]  Android
* [ ]  iOS

5. Other JME4 Projects
* [ ]  Rewrite serializer
~~* [ ]  Breakout jme-examples (see #7 )~~ DONE IN JME3

Things to take into consideration when planning this roadmap:  
* This JME4 will cut support for JDK 8
* There is a laundry list of items that we may or may not want to consider here: https://github.com/jMonkeyEngine/jmonkeyengine/issues/198  
* If there are any changes not being implemented due to breaking compatibility with previous builds, this is the time to make those changes.

About the SDK  
At this time it is *NOT* within the scope of JME4 to prepare a SDK based on Netbeans 10+. 
If someone wants to do this, we would welcome it with open arms, but it will take a massive amount of work, and we already have a lot to do just getting JME4 ready.

**Comment by stephengold** [comment]
Also, please delete the Blender importer.

**Comment by ItsMike54** [comment]
Hey, I know this project is a bit out of date. But I wanted to bring it back up again, these changes should be simply integrated into Master jME at this point.
I've submited a PR to remove JOGL renderer as it has a lot of bugs, and won't be useful for adding Vulkan. And I'm also working on a PR to remove bullet libs.
Also 3.3 introduced a new anim system, so once the old one is removed (not sure if it is, or when), you can check that off.

**Comment by ItsMike54** [comment]
So something to keep in mind is that Riccardo is working on the pipeline, which he says can make the addition of a new renderer (Vulkan) easier. Also we don't need any Vulkan shaders because all we need is a Util class / Gradle task that converts GLSL (OpenGL) to SPIR-V (Vulkan). In fact I have already written a GLSL -> Spirv converter.

**Comment by pavly-gerges** [comment]
Would you like some work on Android? I can prepare a Roadmap for the Android module.

**Comment by tlf30** [comment]
Hello, it was simpler to build a new engine from scratch to be honest. Vulkan (or render independent backend) would require massive changes to jme that would probably not be welcome by the community. Instead I have been building a completely custom engine that solves many of the issues I have had with jme. 

Things in my engine that are far different are:
* Completely component based (different from ECS but similar in concept)
* multiple rendering engine support
* plugin based for features
* server/client based with all data persisted on server (does not support client only, instead the client can run a server in the background for single player) 
* completely multi threaded (including scene graph)

I currently have implemented plugins for supporting:
* PostgreSQL persistence
* OpenGL via LWJGL
* Vulkan via LWJGL
* GLFW via LWJGL
* ImGui for UI 
* Groovy, JavaScript, and kotlin scripting engines for client and server. 

I am in the process of implementing a Physx5 plugin for physics, and when I get to it an OpenAL plugin. 

The rendering engine design allows for a fully programmable rendering pipeline independent of the material and shader pipelines. It can be complicated to understand at first but very powerful. Currently it does not support G buffers or custom inputs/outputs between rendering stages, but does for shaders and material stages. I am still working on the PBR lighting implementation.  

Other things that still need to be done that I have not looked at:
* Terrain
* animation system

The model/mesh components allow very good bone and morph key data structures/control. So I think building a tween based animation system would not be too complicated, but I have not started.

Originally the engine used a iso surface terrain engine based on code from the jme community that I patched together and modified for the engine. I need to rewrite that code for the new scene graph and backend, but also fix many issues in it. I will probably just write most of it from scratch. 

I have been hesitant to make it open source yet due to the large amount of breaking changes that I make on a regular basis. The engines code is originally from 2018 and in the past used JME for the rendering engine and scene graph. So several key parts of the engine are currently broken due to cutting the engine over to use its own rendering engine and scene graph. Other parts have ugly hacks to keep things working until I have time to rewrite them.

If people are interested, I can share access to the code, it is currently hosted on a private gitlab instance. PM me on the forums for more information. 

Thanks,
Trevor

**Comment by stephengold** [comment]
I've often considered doing something similar to what you describe. It's a big project.

If I were building a game engine from scratch, one of the first things I would do is ditch com.jme3.math and use JOML instead.

**Comment by tlf30** [comment]
That is exactly what I did.

**Comment by bobcbui** [comment]
Are you still trying this task?

**Comment by tlf30** [comment]
No, this is left here for documentation. Once the jme4 effort re-kicks off, then I will be involved with that. This repo is not active and there are no current plans to continue work here.

EDIT: If you are asking about my custom engine from scratch, that is an ongoing effort.
